services:
  web:
    build: .
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_ENV=${DJANGO_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      # Optionnel : création auto du superuser
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      # En production, on ne monte que les médias et static
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 80000
    command: gunicorn
    networks:
      - garantix_network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: garantix_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - garantix_network
    expose:
      - 5432

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  garantix_network:
    driver: bridge